lecture/web/django/board/urls.py
from django.urls import path

from . import views

app_name = 'board'

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:question_id>/',views.detail,name='detail'),
    path('answer/create/<int:question_id>/',views.answer_create,name='answer_create'),
    path('question/create/',views.question_create,name='question_create'),
]

lecture/web/django/config/urls.py
from django.contrib import admin
from django.urls import path , include

from board import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/',include('board.urls')),
]

lecture/web/django/board/models.py
from django.db import models

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField()
    
    def __str__(self):
        return self.subject
    
    
class Answer(models.Model):
    Question = models.ForeignKey(Question,on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField()

# Create your models here.

lecture/web/django/board/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.utils import timezone
from .models import Question , Answer

def index(request):
    # return HttpResponse('안녕하세요. board의 index 페이지입니다')
    question_list = Question.objects.order_by('-created_at')
    context = {'question_list': question_list}
    return render(request, 'board/question_list.html',context)
# Create your views here.

def detail(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    context = {'question':question}
    return render(request,'board/question_detail.html',context)

def answer_create(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    answer = Answer(question=question, content=request.POST.get('content'), created_at=timezone.now())
    answer.save()
    return redirect('board:detail',question_id=question.id)

lecture/web/django/templates/board/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django board</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
    crossorigin="anonymous">
</head>
<body>
    <!-- 기본 템플릿 안에 삽입될 내용-->
    {% block content %}
    {% endblock %}

<!--boot strap-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" 
    crossorigin="anonymous"></script>
</body>
</html>

lecture/web/django/templates/board/question_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container my-3">
        <!-- 질문 -->
        <h2 class="border-bottom py-2">{{ question.subject }}</h2>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
                <div class="d-flex justify-content-end">
                    <div class="badge bg-light text-dark p-2">
                        {{ question.created_at}}
                    </div>
                </div>
            </div>
        </div>
        <!-- 답변-->
        <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다</h5>
        {% for answer in question.answer_set.all %}
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                <div class="d-flex justify-content-end">
                    <div class="badge bg-light text-dark p-2">
                        {{ answer.created_at }}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <!-- 답변 등록 -->
        <form action="{% url 'board:answer_create' question.id %}" method="post" class="my-3">
            {% csrf_token %}
            <div class="mb-3">
                <label for="content" class="form-label">답변내용</label>
                <textarea name="content" id="content" class="form-control" rows="10"></textarea>
            </div>
            <input type="submit" value="답변등록" class="btn btn-primary">
        </form>
    </div>
{% endlock %}

lecture/web/django/templates/board/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class='container my-3'>
    <table class="table">
        <thead>
        <tr class="'table=dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'board:detail' question.id %}">{{ question.subject }}</a>
            </td>
                <td>{{ question.created_at }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
            </table>
    <a href="{% url 'board:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}